In [1]:
import numpy as np
X = np.array(([2,9] , [1,5], [3,6],[6,9],[10,8],[10,5],[5,10],[5,13]),dtype = float)
y = np.array(([92],[86],[89],[94],[96],[93],[93],[94]),dtype = float)
print X
print y
# scale the data
X = X/ np.amax(X)
y = y/100
print X
print y

[[ 2.  9.]
 [ 1.  5.]
 [ 3.  6.]
 [ 6.  9.]
 [10.  8.]
 [10.  5.]
 [ 5. 10.]
 [ 5. 13.]]
[[92.]
 [86.]
 [89.]
 [94.]
 [96.]
 [93.]
 [93.]
 [94.]]
[[0.15384615 0.69230769]
 [0.07692308 0.38461538]
 [0.23076923 0.46153846]
 [0.46153846 0.69230769]
 [0.76923077 0.61538462]
 [0.76923077 0.38461538]
 [0.38461538 0.76923077]
 [0.38461538 1.        ]]
[[0.92]
 [0.86]
 [0.89]
 [0.94]
 [0.96]
 [0.93]
 [0.93]
 [0.94]]


In [7]:
class NeuralNetwork():
    def __init__(self):
        # define the parameters
        self.in_size = 2
        self.out_size = 1
        self.hidden_size = 3
        
        self.W1 = np.random.rand(self.in_size,self.hidden_size)
        self.W2 = np.random.rand(self.hidden_size ,self.out_size)
    def sigmoid(self,s,deriv = False):
        if(deriv == True):
            return s*(1-s)
        else:
            return  1/(1+np.exp(-s))
    def feedForward(self,X):
        self.z =np.dot(X,self.W1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2,self.W2)
        output = self.sigmoid(self.z3)
        return output
    def backward(self,X,y,output):
        self.error_out = y - output # error in output
        self.out_delta =self.error_out * self.sigmoid(output ,deriv = True) 
        
        self.z2_error = self.out_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv = True)
        
        self.W1  +=X.T.dot(self.z2_delta)
        self.W2  += self.z2.T.dot(self.out_delta)
    def train(self,X,y):
        output= self.feedForward(X)
        self.backward(X,y,output)

NN = NeuralNetwork() 
print str(NN.feedForward(X))
print "***********************"
for i in range(1000):
    if(i % 100 ==0 ):
        print " loss :"+ str(np.mean(np.square(y-NN.feedForward(X))))
    NN.train(X,y)
print " inputs : "+str(X)
print "original  : "+str(y)
print " loss :"+ str(np.mean(np.square(y-NN.feedForward(X)))) 
print
print "final output : "+str(NN.feedForward(X))


[[0.57944836]
 [0.57442995]
 [0.57876201]
 [0.58619545]
 [0.59177345]
 [0.58951183]
 [0.58529777]
 [0.58746397]]
***********************
 loss :0.11427458671763652
 loss :0.0003042185154778921
 loss :0.00029206689833091774
 loss :0.00028134050002941646
 loss :0.0002718083686252423
 loss :0.00026328839263882106
 loss :0.0002556328707772596
 loss :0.00024872090309992884
 loss :0.00024245268252309733
 loss :0.0002367451633256437
 inputs : [[0.15384615 0.69230769]
 [0.07692308 0.38461538]
 [0.23076923 0.46153846]
 [0.46153846 0.69230769]
 [0.76923077 0.61538462]
 [0.76923077 0.38461538]
 [0.38461538 0.76923077]
 [0.38461538 1.        ]]
original  : [[0.92]
 [0.86]
 [0.89]
 [0.94]
 [0.96]
 [0.93]
 [0.93]
 [0.94]]
 loss :0.00023152873942054405

final output : [[0.91078926]
 [0.88915546]
 [0.90499866]
 [0.92769039]
 [0.93789061]
 [0.93119682]
 [0.9266344 ]
 [0.93373259]]
